name: Get Secrets from Key Vault

on:
  workflow_dispatch:

jobs:
  get-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to Azure
        uses: equinor/AzConnect@v1
        with:
          TenantID: ${{ vars.AZ_TENANT_ID }}
          Subscription: ${{ vars.AZ_SUBSCRIPTION_ID }}
          AppID: ${{ vars.AZ_CLIENT_ID }}
          AppSecret: ${{ secrets.AZ_CLIENT_SECRET }}

      - name: Get Key Vault Secrets
        shell: pwsh
        run: |
          $KeyVaultName = "github-keyvault-kv"
          $SecretNamesList = "my-secret,another-secret,nonexisting-secret"

          $SecretsDictionary = @{}
          $SecretNamesList -split ',' | ForEach-Object {
              
              Write-Output "Key: $_"

              try {
                  $SecretValue = Get-AzKeyVaultSecret -VaultName $KeyVaultName -Name $_
                  $SecretValueText = ConvertFrom-SecureString -SecureString $SecretValue.SecretValue -AsPlainText
              }
              catch {
                  $SecretValueText = $null
              }

              if ($null -ne $SecretValueText)
              {
                  $SecretsDictionary.Add($_, $SecretValueText)
              }
          }

          $SecretsDictionary.Keys | ForEach-Object {
              $Msg = "{0} = {1}" -f $_, $SecretsDictionary[$_]
              Write-Output $Msg
          }

          Write-Output "Finished"
